In [10]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
import numpy as np
import os
import datetime as dt

In [28]:
nat_disasters_path = "Natural disasters.csv"
nat_disasters_cost_path = "disaster_cost.csv"
nat_disastersdata = pd.read_csv(nat_disasters_path)
nat_disastercost = pd.read_csv(nat_disasters_cost_path)
# nat_disastersdata
# nat_disastercost

frames = [nat_disastersdata, nat_disastercost]

result = pd.concat(frames)
result

,Year,fema_declaration_string,disaster_number,state,declaration_type,declaration_date,incident_type,declaration_title,ih_program_declared,ia_program_declared,...,declaration_request_number,last_ia_filing_date,hash,last_refresh,id,Death toll,Damage costUS$,Main article,Location,Notes
0,1953,DR-1-GA,1.0,GA,DR,1953-05-02T00:00:00Z,Tornado,Tornado,0.0,1.0,...,53013.0,NaN,d79586ee70f2ea4bc33a5b3ea900902fda5131c1,2022-04-26T19:03:06Z,60c3b7a9a0ee349d71025780,NaN,NaN,NaN,NaN,NaN
1,1953,DR-2-TX,2.0,TX,DR,1953-05-15T00:00:00Z,Tornado,Tornado & Heavy Rainfall,0.0,1.0,...,53003.0,NaN,8784655a1395087b17c39b9f7422a5fd1db7826d,2022-04-26T19:03:06Z,60c3b7a9a0ee349d71025783,NaN,NaN,NaN,NaN,NaN
2,1953,DR-3-LA,3.0,LA,DR,1953-05-29T00:00:00Z,Flood,Flood,0.0,1.0,...,53005.0,NaN,b3da3033d2f91ad92b632eb7fa738b52df4fe07d,2022-04-26T19:03:06Z,60c3b7a9a0ee349d71025777,NaN,NaN,NaN,NaN,NaN
3,1953,DR-4-MI,4.0,MI,DR,1953-06-02T00:00:00Z,Tornado,Tornado,0.0,1.0,...,53004.0,NaN,53ea4b01cfae0448d980cc14d4487b78f95f80ad,2022-04-26T19:03:06Z,60c3b7a9a0ee349d7102577a,NaN,NaN,NaN,NaN,NaN
4,1953,DR-5-MT,5.0,MT,DR,1953-06-06T00:00:00Z,Flood,Floods,0.0,1.0,...,53006.0,NaN,92c957fa1f5009efd24996a39bd9474e11a3ea89,2022-04-26T19:03:06Z,60c3b7a9a0ee349d71025774,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,1888,NaN,NaN,NaN,NaN,NaN,Blizzard,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,400,NaN,Great Blizzard of 1888,NJ,Fatalities estimated
145,1888,NaN,NaN,NaN,NaN,NaN,Cold wave,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,1888 Northwest Cold Wave,OH,NaN
146,1871,NaN,NaN,NaN,NaN,NaN,Wildfire,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2500,NaN,Peshtigo fire,WI,Deadliest firestorm in United States history
147,1862,NaN,NaN,NaN,NaN,NaN,Flood,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,5000,100000000.0,Great Flood of 1862,CA,An atmospheric river led to 43 continuous days...
148,1816,NaN,NaN,NaN,NaN,NaN,Famine (caused by volcano),NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,Year Without a Summer,NaN,Volcanic dust from a massive eruption by Mount...

In [37]:
# nat_disastersdata = 
nat_disaster_year = result.sort("Year")
# nat_disaster_year = nat_disaster_year["Year"].count()
nat_disaster_year

# nat_disaster_type = result.groupby("incident_type")
# nat_disaster_type = nat_disaster_type["incident_type"].count()
# nat_disaster_type

incident_type
Avalanche                                        1
Biological                                    7857
Blizzard                                        10
Chemical                                         9
Coastal Storm                                  639
Cold wave                                        2
Dam/Levee Break                                 13
Drought                                       1293
Earthquake                                     231
Earthquake and fire (urban conflagration)        1
Famine (caused by volcano)                       1
Fire                                          3594
Fishing Losses                                  42
Flood                                        10537
Freezing                                       301
Heat wave                                        3
Heat wave and Drought                            1
Human Cause                                      7
Hurricane                                    12541
Hurricane and Flood                              1
Landslide                                        1
Mud/Landslide                                   36
Mudflow                                          1
Other                                          306
Severe Ice Storm                              2942
Severe Storm(s)                              17290
Snow                                          3696
Snow storm                                       3
Storm                                            1
Terrorist                                        5
Tornado                                       1588
Toxic Substances                                 9
Tropical storm                                   1
Tsunami                                         11
Tsunami and Earthquake                           2
Typhoon                                        130
Volcano                                         52
Wildfire                                        18
Wildfires                                        1
Winter storm                                     1
Winter storm and flood                           1
Name: incident_type, dtype: int64